services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: linda
      RABBITMQ_DEFAULT_PASS: linda
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis
    ports:
      - "6379:6379"
  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: token
      SRH_CONNECTION_STRING: "redis://redis:6379"

volumes:
  rabbitmq_data:

