apiVersion: v1
kind: ConfigMap
metadata:
  name: linda-config
  namespace: linda
  labels:
    app: linda-assistant
data:
  RABBITMQ_URL: "amqp://linda:linda@rabbitmq.linda.svc.cluster.local:5672"
  MEM0_BASE_URL: "http://mem0.linda.svc.cluster.local:8000"
  MEM0_VECTOR_STORE_PROVIDER: "upstash_vector"
  CELERY_BASE_URL: "http://celery.linda.svc.cluster.local:8000"
  BACKEND_INTERNAL_URL: "http://linda-frontend-service.linda.svc.cluster.local:3000"
  CHROME_URL: "ws://headless-chrome.linda.svc.cluster.local:9222"
  NEXT_PUBLIC_APP_URL: "https://linda.rxlab.app"
