apiVersion: v1
kind: Service
metadata:
  name: mem0
  namespace: linda
  labels:
    app: mem0
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: mem0
