name: iOS CI

on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios:
    name: Build iOS App
    uses: ./.github/workflows/ios-setup.yml
    with:
      job-name: Build iOS App
      script: ios-build.sh
      scheme: LindaAssistant
      configuration: Debug
      sdk: iphonesimulator
      artifact-name: ios-build-logs
      runs-on: '"self-hosted", "macOS"'
      artifact-path: build.log
    secrets: inherit

  build-macos:
    name: Build macOS App
    uses: ./.github/workflows/ios-setup.yml
    with:
      job-name: Build macOS App
      script: macos-build.sh
      scheme: LindaAssistant
      configuration: Debug
      sdk: macosx
      runs-on: '"self-hosted", "macOS"'
      artifact-name: macos-build-logs
      artifact-path: build-macos.log
    secrets: inherit

  test:
    name: Run iOS Tests
    uses: ./.github/workflows/ios-setup.yml
    with:
      runs-on: '"self-hosted", "macOS"'
      job-name: Run iOS Tests
      script: ios-test-plan.sh
      scheme: LindaAssistant
      configuration: Debug
      sdk: iphonesimulator
      artifact-name: test-logs
      artifact-path: test.log
      upload-test-results: true
      start-backend: true
      parallel-testing-workers: 2
    secrets: inherit

  test-macos:
    if: false
    name: Run macOS Tests
    uses: ./.github/workflows/ios-setup.yml
    with:
      runs-on: '"self-hosted", "macOS"'
      job-name: Run macOS Tests
      script: ios-test-plan.sh
      scheme: LindaAssistant
      configuration: Debug
      sdk: macosx
      artifact-name: macos-test-logs
      artifact-path: test.log
      upload-test-results: true
      start-backend: true
    secrets: inherit
